"""add_coupon_flags_hot_homepage

Revision ID: 0b37ba28a71c
Revises: 6efcb23907d3
Create Date: 2025-10-10 12:39:39.674374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b37ba28a71c'
down_revision = '6efcb23907d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, adding NOT NULL requires a server_default to backfill existing rows
    op.add_column('coupons', sa.Column('hot_deal', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('coupons', sa.Column('show_on_homepage', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'show_on_homepage')
    op.drop_column('coupons', 'hot_deal')
    # ### end Alembic commands ###
