"""Initial migration

Revision ID: 0c87f99bc8e6
Revises: 
Create Date: 2025-09-17 00:32:41.495576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c87f99bc8e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_coupons', sa.Integer(), nullable=True),
    sa.Column('social_links', sa.String(length=200), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('headquarters', sa.String(length=100), nullable=True),
    sa.Column('return_policy', sa.String(length=100), nullable=True),
    sa.Column('shipping_info', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('store_id', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('discount_type', sa.String(length=50), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('discounted_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('terms_conditions', sa.String(length=255), nullable=True),
    sa.Column('usage_instructions', sa.String(length=255), nullable=True),
    sa.Column('minimum_order', sa.Float(), nullable=True),
    sa.Column('maximum_discount', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('deal_type', sa.String(length=50), nullable=True),
    sa.Column('applicable_products', sa.String(length=255), nullable=True),
    sa.Column('exclusions', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_category',
    sa.Column('store_id', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id', 'category_id')
    )
    op.create_table('coupon_category',
    sa.Column('coupon_id', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupon_category')
    op.drop_table('store_category')
    op.drop_table('coupons')
    op.drop_table('stores')
    op.drop_table('categories')
    # ### end Alembic commands ###
